# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0004_hotel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lake',
            name='status',
            field=models.CharField(default='Not-Approved', max_length=50),
        ),
        migrations.AddField(
            model_name='national_park',
            name='status',
            field=models.CharField(default='Not-Approved', max_length=50),
        ),
        migrations.AddField(
            model_name='temple',
            name='status',
            field=models.CharField(default='Not-Approved', max_length=50),
        ),
    ]
