# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-30 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular', '0006_new_popular_hotel1_annualreport_2017_new_popular_hotel2_annualreport_2017_new_popular_hotel3_annualr'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_popular_permit_office_annualReport_2011',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=10)),
                ('national_count', models.BigIntegerField()),
                ('international_count', models.BigIntegerField()),
                ('male_count', models.BigIntegerField()),
                ('female_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new_popular_permit_office_annualReport_2012',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=10)),
                ('national_count', models.BigIntegerField()),
                ('international_count', models.BigIntegerField()),
                ('male_count', models.BigIntegerField()),
                ('female_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new_popular_permit_office_annualReport_2013',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=10)),
                ('national_count', models.BigIntegerField()),
                ('international_count', models.BigIntegerField()),
                ('male_count', models.BigIntegerField()),
                ('female_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new_popular_permit_office_annualReport_2014',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=10)),
                ('national_count', models.BigIntegerField()),
                ('international_count', models.BigIntegerField()),
                ('male_count', models.BigIntegerField()),
                ('female_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new_popular_permit_office_annualReport_2015',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=10)),
                ('national_count', models.BigIntegerField()),
                ('international_count', models.BigIntegerField()),
                ('male_count', models.BigIntegerField()),
                ('female_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='new_popular_permit_office_annualReport_2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=10)),
                ('national_count', models.BigIntegerField()),
                ('international_count', models.BigIntegerField()),
                ('male_count', models.BigIntegerField()),
                ('female_count', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_september_2017',
            new_name='new_popular_hotel10_october_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_december_2017',
            new_name='new_popular_hotel11_november_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_january_2017',
            new_name='new_popular_hotel12_december_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_may_2017',
            new_name='new_popular_hotel1_january_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_march_2017',
            new_name='new_popular_hotel2_february_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_august_2017',
            new_name='new_popular_hotel3_march_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_october_2017',
            new_name='new_popular_hotel4_april_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_june_2017',
            new_name='new_popular_hotel5_may_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_july_2017',
            new_name='new_popular_hotel6_june_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_april_2017',
            new_name='new_popular_hotel7_july_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_february_2017',
            new_name='new_popular_hotel8_august_2017',
        ),
        migrations.RenameModel(
            old_name='new_popular_hotel_november_2017',
            new_name='new_popular_hotel9_september_2017',
        ),
    ]
